'use client';
import { useEffect, useState } from 'react';
import Link from 'next/link';
import DemoBar from '../components/DemoBar';
import { formatDemoDate, getDemoState, getTodayQueue } from '../../lib/store/demoStore';
import type { Patient, QueueEntry } from '../../lib/types/clinic';
import { getActiveClinic } from '../../lib/store/clinicStore';

export default function ReceptionistDashboard() {
  const [queue, setQueue] = useState<QueueEntry[]>([]); const [patients, setPatients] = useState<Patient[]>([]); const [clinicName, setClinicName] = useState('Mehta Family Clinic');
  useEffect(() => { const load = () => { const state = getDemoState(); setQueue(getTodayQueue()); setPatients(state.patients); setClinicName(getActiveClinic().name); }; const timer = window.setTimeout(load, 0); window.addEventListener('demo-state-change', load); return () => { window.clearTimeout(timer); window.removeEventListener('demo-state-change', load); }; }, []);
  const person = (id: string) => patients.find((item) => item.id === id); const waiting = queue.filter((item) => item.status === 'WAITING'); const active = queue.filter((item) => item.status === 'IN_CONSULTATION'); const done = queue.filter((item) => item.status === 'COMPLETED');
  return <div className="min-h-screen bg-slate-50"><DemoBar /><header className="h-16 bg-white border-b px-8 flex items-center justify-between"><Link href="/" className="text-blue-700 font-bold text-lg">{clinicName}</Link><nav className="flex gap-6 text-sm"><span className="font-semibold text-blue-700">Reception</span><Link href="/doctor/queue">Doctor Queue</Link><Link href="/settings">Settings</Link></nav></header>
    <main className="max-w-6xl mx-auto px-8 py-8"><div className="flex items-end justify-between"><div><p className="text-sm text-blue-700 font-semibold">FRONT DESK</p><h1 className="text-3xl font-bold">Good morning</h1><p className="text-slate-500 mt-1">{formatDemoDate(new Date().toISOString())}</p></div><Link href="/receptionist/search" className="bg-blue-700 text-white rounded-lg px-6 py-3 font-semibold">Start demo: find a patient →</Link></div>
      <div className="grid grid-cols-3 gap-5 mt-8"><Stat label="Waiting" value={waiting.length} color="amber" /><Stat label="In consultation" value={active.length} color="blue" /><Stat label="Completed" value={done.length} color="emerald" /></div>
      <section className="bg-white border rounded-2xl mt-8 overflow-hidden"><div className="px-6 py-5 border-b flex justify-between"><div><h2 className="font-bold text-xl">Next patients</h2><p className="text-sm text-slate-500">Live from today’s queue</p></div><Link href="/doctor/queue" className="text-blue-700 font-semibold text-sm">View doctor queue →</Link></div><div className="divide-y">{[...active, ...waiting].map((entry) => <Link key={entry.id} href={`/patient/${entry.patientId}?queue=${entry.id}`} className="px-6 py-5 flex items-center justify-between hover:bg-slate-50"><div className="flex gap-4 items-center"><span className="w-11 h-11 rounded-lg bg-blue-50 text-blue-700 grid place-items-center font-bold">#{String(entry.token).padStart(2, '0')}</span><div><p className="font-semibold">{person(entry.patientId)?.name}</p><p className="text-sm text-slate-500">{entry.complaint}</p></div></div><span className={`text-xs font-bold rounded-full px-3 py-1 ${entry.status === 'IN_CONSULTATION' ? 'bg-blue-50 text-blue-700' : 'bg-amber-50 text-amber-700'}`}>{entry.status === 'IN_CONSULTATION' ? 'IN CONSULTATION' : 'WAITING'}</span></Link>)}</div></section>
    </main></div>;
}
function Stat({ label, value, color }: { label: string; value: number; color: 'amber' | 'blue' | 'emerald' }) { const styles = { amber: 'border-amber-200 bg-amber-50', blue: 'border-blue-200 bg-blue-50', emerald: 'border-emerald-200 bg-emerald-50' }; return <div className={`border rounded-2xl p-6 ${styles[color]}`}><p className="text-sm text-slate-600">{label}</p><p className="text-4xl font-bold mt-2">{value}</p></div>; }
