'use client';
import { FormEvent, useState } from 'react';
import Link from 'next/link';
import DemoBar from '../../components/DemoBar';
import { addPatientToQueue, findPatientByMobile, registerPatient } from '../../../lib/store/demoStore';
import type { Gender, Patient } from '../../../lib/types/clinic';

export default function PatientSearch() {
  const [mobile, setMobile] = useState(''); const [patient, setPatient] = useState<Patient | null>(null); const [searched, setSearched] = useState(false);
  const [name, setName] = useState(''); const [age, setAge] = useState(''); const [gender, setGender] = useState<Gender>('Male'); const [complaint, setComplaint] = useState('');
  const [message, setMessage] = useState(''); const [error, setError] = useState('');
  const search = (value: string) => { const clean = value.replace(/\D/g, '').slice(0, 10); setMobile(clean); setMessage(''); setError(''); if (clean.length === 10) { setPatient(findPatientByMobile(clean) ?? null); setSearched(true); } else { setPatient(null); setSearched(false); } };
  const register = (event: FormEvent) => { event.preventDefault(); setError(''); const parsedAge = Number(age); if (name.trim().length < 2) return setError('Enter the patient’s full name.'); if (!Number.isInteger(parsedAge) || parsedAge < 0 || parsedAge > 120) return setError('Enter an age between 0 and 120.'); try { const created = registerPatient({ name: name.trim(), age: parsedAge, gender, mobile }); setPatient(created); setMessage('Patient registered. You can now add them to the queue.'); } catch (reason) { setError(reason instanceof Error ? reason.message : 'Could not register patient.'); } };
  const queue = () => { if (!patient) return; try { const entry = addPatientToQueue(patient.id, complaint); setMessage(`Token #${String(entry.token).padStart(2, '0')} assigned to ${patient.name}.`); setError(''); } catch (reason) { setError(reason instanceof Error ? reason.message : 'Could not add patient to queue.'); setMessage(''); } };
  return <div className="min-h-screen bg-slate-50 text-slate-900"><DemoBar /><header className="h-16 bg-white border-b px-8 flex items-center justify-between"><Link href="/receptionist" className="font-bold text-lg text-blue-700">Bharat Clinic</Link><nav className="flex gap-6 text-sm"><Link href="/receptionist">Reception</Link><Link href="/doctor/queue">Doctor Queue</Link></nav></header>
    <main className="max-w-5xl mx-auto px-8 py-10"><div className="mb-8"><p className="text-sm text-blue-700 font-semibold">RECEPTION</p><h1 className="text-3xl font-bold">Find or register a patient</h1><p className="text-slate-500 mt-2">Enter a 10-digit mobile number to begin today’s visit.</p></div>
      <div className="grid grid-cols-[1fr_1.15fr] gap-8 items-start"><section className="bg-white border rounded-2xl p-6 shadow-sm"><label className="text-sm font-semibold">Mobile number</label><div className="mt-2 flex border rounded-lg overflow-hidden focus-within:ring-2 ring-blue-200"><span className="px-4 py-3 bg-slate-100 border-r">+91</span><input autoFocus className="flex-1 px-4 outline-none" value={mobile} onChange={(e) => search(e.target.value)} placeholder="98765 43210" inputMode="numeric" /></div><p className="text-xs text-slate-500 mt-2">Try 9876543210 for an existing patient.</p></section>
        <section className="bg-white border rounded-2xl p-6 shadow-sm min-h-80">{!searched && <div className="h-64 flex items-center justify-center text-slate-400">Patient details will appear here</div>}{searched && patient && <div><div className="flex justify-between"><div><p className="text-sm text-emerald-700 font-semibold">Patient found</p><h2 className="text-2xl font-bold mt-1">{patient.name}</h2><p className="text-slate-500">{patient.age} years · {patient.gender} · +91 {patient.mobile}</p></div><Link className="text-blue-700 font-semibold text-sm" href={`/patient/${patient.id}`}>View profile →</Link></div><label className="block text-sm font-semibold mt-7">Reason for visit</label><input className="w-full border rounded-lg px-4 py-3 mt-2" value={complaint} onChange={(e) => setComplaint(e.target.value)} placeholder="e.g. Fever and body ache" /><button onClick={queue} className="w-full mt-4 bg-blue-700 hover:bg-blue-800 text-white rounded-lg py-3 font-semibold">Add to today’s queue</button></div>}
          {searched && !patient && <form onSubmit={register}><p className="text-sm text-amber-700 font-semibold">No patient found</p><h2 className="text-xl font-bold mt-1">Register new patient</h2><div className="grid grid-cols-2 gap-4 mt-5"><label className="col-span-2 text-sm font-semibold">Full name<input className="block w-full border rounded-lg px-3 py-2 mt-1 font-normal" value={name} onChange={(e) => setName(e.target.value)} /></label><label className="text-sm font-semibold">Age<input className="block w-full border rounded-lg px-3 py-2 mt-1 font-normal" value={age} onChange={(e) => setAge(e.target.value.replace(/\D/g, ''))} /></label><label className="text-sm font-semibold">Gender<select className="block w-full border rounded-lg px-3 py-2 mt-1 font-normal" value={gender} onChange={(e) => setGender(e.target.value as Gender)}><option>Male</option><option>Female</option><option>Other</option></select></label></div><button className="w-full mt-5 bg-blue-700 text-white rounded-lg py-3 font-semibold">Register patient</button></form>}
          {message && <p className="mt-4 rounded-lg bg-emerald-50 border border-emerald-200 text-emerald-800 px-4 py-3 text-sm">{message}</p>}{error && <p className="mt-4 rounded-lg bg-red-50 border border-red-200 text-red-800 px-4 py-3 text-sm">{error}</p>}</section></div>
    </main></div>;
}
